import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { IconHamburger, Logo } from './assets/icons/shared'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex justify-between items-center p-6'>
          <Logo height={48} width={48}/>
          <IconHamburger height={24} width={21} />
        </header>
        {children}
      </body>
    </html>
  )
}
