import type { Metadata } from 'next'
import { Barlow, Barlow_Condensed, Bellefair } from 'next/font/google'
import './globals.css'

const barlow = Barlow({
  weight: ['100', '200', '400', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-barlow'
})

const barlowCondensed = Barlow_Condensed({
  weight: ['100', '200', '400', '600', '700', '800'],
  subsets: ['latin'],
  variable: '--font-barlowCondensed'
})

const bellefair = Bellefair({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-bellefair'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${barlow.variable} ${bellefair.variable} ${barlowCondensed.variable}`}>
        {children}
      </body>
    </html>
  )
}
